alert("Hmmm you clicking the right button is a good sign")
alert("Its giving me hope")
alert("not a lot of hope")
alert("but its not like we expected anything coming from you")
alert("alright lets get this over with i got lunch in 10 mins")
alert("Ill be nice to you since you're cute")
alert("dont let that get to you Im just a nice A.I")
alert("Im gonna give you a test")
alert("the rules are simple")
alert("if you get below 5=you're stupid if you get 7 then you're not if you get a perfect score then you cheated")
alert("Got it?")
alert("You get it you're not stupid")
alert("I mean you have no choice but to get it cause im not saying it again well unless you restart the tab but I would repeat all the stuff I said and you dont want that do you?")
alert("Lets just continue")
alert("Copy this link Im about to show you and paste it on google")
alert("https://forms.gle/rWNY8bfBiYTwRGAy6")
